// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFnMbye0wSip6yHqFGQLkoQGRYmbEw0mI',
    appId: '1:731704599259:web:7fe7be9229ce16ce61e2fe',
    messagingSenderId: '731704599259',
    projectId: 'grocery-shopping--app',
    authDomain: 'grocery-shopping--app.firebaseapp.com',
    storageBucket: 'grocery-shopping--app.appspot.com',
    measurementId: 'G-Y21RD7WTV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5D8yZ-I4zGOA7dRW4uqelbTUimuU9z6g',
    appId: '1:731704599259:android:540ae41d1325f23d61e2fe',
    messagingSenderId: '731704599259',
    projectId: 'grocery-shopping--app',
    storageBucket: 'grocery-shopping--app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5DUiL7NvB6u8SewDlxHigyJf2yis7gQQ',
    appId: '1:731704599259:ios:31ee6ad2de5025a961e2fe',
    messagingSenderId: '731704599259',
    projectId: 'grocery-shopping--app',
    storageBucket: 'grocery-shopping--app.appspot.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5DUiL7NvB6u8SewDlxHigyJf2yis7gQQ',
    appId: '1:731704599259:ios:cafa82fbd0c76e4161e2fe',
    messagingSenderId: '731704599259',
    projectId: 'grocery-shopping--app',
    storageBucket: 'grocery-shopping--app.appspot.com',
    iosBundleId: 'com.example.groceryApp.RunnerTests',
  );
}
